PUT http://localhost:5000/api/hop-dong
Content-Type: application/json

{
    "MaHDong": 1,
    "CmndNguoiDDHDong": "251198073",
    "SoThangGiaHan": 3
}


###
PUT http://localhost:5000/api/hop-dong
Content-Type: application/json

{
    "MaHDong": 1,
    "CmndNguoiDDHDong": "251198073",
    "SoThangGiaHan": 1
}

###
PUT http://localhost:5000/api/hop-dong-error
Content-Type: application/json

{
    "MaHDong": 1,
    "CmndNguoiDDHDong": "251198073",
    "SoThangGiaHan": 1
}

###
PUT http://localhost:5000/api/hop-dong-error
Content-Type: application/json

{
    "MaHDong": 1,
    "CmndNguoiDDHDong": "251198073",
    "SoThangGiaHan": 3
}

###
GET http://localhost:5000/api/hop-dong



#######################'

###
GET http://localhost:5000/api/phantom/taixe-khuvuc/8
Content-Type: application/json




###
POST http://localhost:5000/api/phantom/home
Content-Type: application/json

{
	"MaDHang": 4,
    "MaHHoa": 1, 
	"Soluong": 5
}

###
PUT

### 
DELETE http://localhost:5000/api/phantom/xoa-tai-xe/8

### 
DELETE http://localhost:5000/api/phantom/xoa-tai-xe-error/8


###
POST http://localhost:5000/api/phantom/taixe-them-khuvuc
Content-Type: application/json

{
	"MaTXe": 8,
    "MaKVuc": 1 
}

###
GET http://localhost:5000/api/phantom/tai-xe

//////////////////////////////////////
###
GET http://localhost:5000/api/dirty-read/doi-tac

// Trước
###
POST http://localhost:5000/api/dirty-read/them-hanghoa-vao-chinhanh
Content-Type: application/json

{
    "MaHHoa": 6,
    "SoLuongTon": 10,
    "MaCNhanh": 1
}


// Sau
###
GET http://localhost:5000/api/dirty-read/xem-ds-hanghoa-doitac-error/1


###
GET http://localhost:5000/api/dirty-read/xem-ds-hanghoa-doitac/1


###
GET http://localhost:5000/api/unrepeatable-read/khu-vuc

// RUN FIRST
// Error
###
GET http://localhost:5000/api/unrepeatable-read/xem-thongtin-chitiet-khuvuc-error/2

// Fixed
###
GET http://localhost:5000/api/unrepeatable-read/xem-thongtin-chitiet-khuvuc/5


// RUN SECOND
###
PUT http://localhost:5000/api/unrepeatable-read/thaydoi-khuvuc-taixe
Content-Type: application/json

{
    "MaTXe": 3,
    "MaKVucCu": 1,
    "MaKVucMoi": 2
}

// ERROR
###
DELETE  http://localhost:5000/api/conversion-deadlock/xoa-taixe-khuvuc-error
Content-Type: application/json

{
    "MaTXe": 1,
    "MaKVuc": 1
}

###
DELETE http://localhost:5000/api/conversion-deadlock/xoa-tatca-taixe-cua-khuvuc-error/1


// FIXED
###
DELETE http://localhost:5000/api/conversion-deadlock/xoa-taixe-khuvuc
Content-Type: application/json

{
    "MaTXe": 3,
    "MaKVuc": 1
}

###
DELETE http://localhost:5000/api/conversion-deadlock/xoa-tatca-taixe-cua-khuvuc/1